In [28]:
#1. Write a function to compute 5/0 and use try/except to catch the exceptions.

def Compute_DIV(Num1, Num2):
    
    try:
        Result = Num1/Num2
        print("Output is " +str(Result))
        
    except ZeroDivisionError:
        print("\nError Occured while processing. Divisible by zero error...!!!")
    
    finally:
        if(Num2 == 0):
            print("\n0 cannot be used as denominator. Try with different number...")
        else:
                print("Inside Finally !!! Calculation Successful !!!")
            
Num1 = int(input("Enter The Number 1 : " + " "))
Num2 = int(input("Enter The Number 2 : " + " "))
Compute_DIV(Num1, Num2)

Enter The Number 1 :  5
Enter The Number 2 :  0

Error Occured while processing. Divisible by zero error...!!!

0 cannot be used as denominator. Try with different number...


In [5]:
#2. Implement a Python program to generate all sentences where subject is in ["Americans",
#Indians] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
#Hint: Subject,Verb and Object should be declared in the program as shown below.
#subjects=["Americans ","Indians"]
#verbs=["play","watch"]
#objects=["Baseball","Cricket"]
#Output should come as below:
#Americans play Baseball.
#Americans play Cricket.
#Americans watch Baseball.
#Americans watch Cricket.
#Indians play Baseball.
#Indians play Cricket.
#Indians watch Baseball.
#Indians watch Cricket.

Subjects=["Americans","Indians"]
Verbs=["play","watch"]
Objects=["Baseball","Cricket"]

Statement=[(Subject+" "+Verb+" "+Object) for Subject in subjects for Verb in verbs for Object in objects]

for sent in Statement:
    print(sent)

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [26]:
#Task 2:
#1. Write a function so that the columns of the output matrix are powers of the input vector.
#The order of the powers is determined by the increasing boolean argument. Specifically, when
#increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.
#HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

import numpy as np

def func_myvander(x, N=None, increasing=False):
    if increasing==False:
        return (np.column_stack([x**(N-i-1) for i in range(N)]))
    else:
        return (np.column_stack([x**(i) for i in range(0,N)]))

x=np.arange(5)
print("Your Input is : ",x,"\n")
N=5
print("Decreasing Stage","\n")
print(25*"-","\n")
print(func_myvander(x,N,False))
print(25*"-","\n")

print("Increasing Stage","\n")
print(25*"-","\n")
print(func_myvander(x,N,True))

Your Input is :  [0 1 2 3 4] 

Decreasing Stage 

------------------------- 

[[  0   0   0   0   1]
 [  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]]
------------------------- 

Increasing Stage 

------------------------- 

[[  1   0   0   0   0]
 [  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]]
